# The latest version supported by both Docker Desktop for Windows and Shippable.
version: "3.6"

services:
  # This service contains the project and runs the tests.
  project:
    entrypoint: "tail -f /dev/null"
    image: mcr.microsoft.com/dotnet/core/sdk:3.0.100-buster
    volumes:
      - ./:/app
